"""
Markdown report formatter.

Produces GitHub-compatible markdown with tables.
No HTML — CommonMark only.
"""

from __future__ import annotations

from mcp_test_harness import __version__
from mcp_test_harness.report.collector import ReportCollector, SuiteReport
from mcp_test_harness.report.scoring import calculate_score, categorize_suite, score_to_grade

_STATUS_SYMBOLS = {
    "pass":  "\u2713 Pass",
    "fail":  "\u2717 Fail",
    "warn":  "\u26a0 Warn",
    "skip":  "\u25cb Skip",
    "error": "! Error",
}

_SECTION_NAMES = {
    "conformance":  "Conformance",
    "security":     "Security",
    "operational":  "Operational",
}


def _suite_summary_line(suite: SuiteReport) -> str:
    parts: list[str] = []
    if suite.passed:
        parts.append(f"**{suite.passed} passed**")
    if suite.failed:
        parts.append(f"**{suite.failed} failed**")
    if suite.warned:
        parts.append(f"{suite.warned} {'warning' if suite.warned == 1 else 'warnings'}")
    if suite.skipped:
        parts.append(f"{suite.skipped} skipped")
    if suite.errored:
        parts.append(f"{suite.errored} {'error' if suite.errored == 1 else 'errors'}")
    return ", ".join(parts) if parts else "0 tests"


def _totals_line(collector: ReportCollector) -> str:
    d = collector.to_dict()["totals"]
    parts: list[str] = []
    if d["passed"]:
        parts.append(f"{d['passed']} passed")
    if d["failed"]:
        parts.append(f"{d['failed']} failed")
    if d["warned"]:
        parts.append(f"{d['warned']} {'warning' if d['warned'] == 1 else 'warnings'}")
    if d["skipped"]:
        parts.append(f"{d['skipped']} skipped")
    if d["errored"]:
        parts.append(f"{d['errored']} {'error' if d['errored'] == 1 else 'errors'}")
    return ", ".join(parts) if parts else "0 tests"


def format_markdown_report(collector: ReportCollector) -> str:
    lines: list[str] = []
    d = collector.to_dict()

    score = d["score"]
    grade = d["grade"]
    grade_label = d["grade_label"]

    server = d["server_info"]
    if server:
        server_str = f"{server.get('name', '?')} v{server.get('version', '?')}"
    else:
        server_str = "unknown"

    # Header
    lines.append("# MCP Test Harness Report")
    lines.append("")
    lines.append("| | |")
    lines.append("|---|---|")
    lines.append(f"| **Server** | {server_str} |")
    lines.append(f"| **Spec** | {d['spec_version']} |")
    lines.append(f"| **Transport** | {d['transport']} |")
    lines.append(f"| **Score** | {score}/100 ({grade} \u2014 {grade_label}) |")
    lines.append(f"| **Date** | {d['timestamp']} |")
    lines.append("")

    # Group suites by category
    grouped: dict[str, list[SuiteReport]] = {
        "conformance": [],
        "security": [],
        "operational": [],
    }
    for suite in collector._suites:
        cat = categorize_suite(suite.name)
        grouped.setdefault(cat, []).append(suite)

    lines.append("## Results")

    for category in ("conformance", "security", "operational"):
        suites = grouped.get(category, [])
        if not suites:
            continue

        lines.append("")
        lines.append(f"### {_SECTION_NAMES.get(category, category.title())}")
        lines.append("")
        lines.append("| Test | Status | Detail |")
        lines.append("|---|---|---|")

        for suite in suites:
            for test in suite.tests:
                sym = _STATUS_SYMBOLS.get(test.status, "?")
                detail_cell = test.detail if test.status != "pass" else ""
                lines.append(f"| {test.name} | {sym} | {detail_cell} |")

            lines.append("")
            lines.append(_suite_summary_line(suite))
            lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append("")
    lines.append(_totals_line(collector))
    lines.append("")
    lines.append("---")
    lines.append(
        f"*Generated by [mcp-test-harness](https://datasculptures.com) v{__version__}*"
    )

    return "\n".join(lines)
